# [hostname]
# ssh_only = true
# format = "[$ssh_symbol](bold blue) on [$hostname]($style) "
# trim_at = "."
# disabled = false


[aws]
symbol = "  "

[conda]
format = '\[[$symbol$environment($version)]($style)\]'

[docker_context]
symbol = " "

[git_branch]
symbol = " "

[nodejs]
format = 'via [$symbol]($style)'

[python]
symbol = " "
format = 'via [$symbol($version)]($style)'

[rlang]
format = 'via [$symbol]($style)'

[rust]
format = 'via [$symbol]($style)'