# [hostname]
# ssh_only = true
# format = "[$ssh_symbol](bold blue) on [$hostname]($style) "
# trim_at = "."
# disabled = false


[aws]
symbol = "  "
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = 'bold blue'

[aws.region_aliases]
ap-southeast-2 = 'au'
us-east-1 = 'va'

[aws.profile_aliases]
CompanyGroupFrobozzOnCallAccess = 'Frobozz'

[conda]
format = '\[[$symbol$environment($version)]($style)\]'
ignore_base = true

[docker_context]
symbol = " "
format = 'via [$symbol$context]($style) '

[git_branch]
symbol = " "

[nodejs]
format = 'via [$symbol]($style)'

[python]
symbol = " "
format = 'via [$symbol($version)]($style)'

[rlang]
format = 'via [$symbol]($style)'

[rust]
format = 'via [$symbol]($style)'